class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_title': 'أكاديمية طيبة المتكاملة',
      'thebes_academy': 'Thebes Academy',
      'welcome_back': 'أهلاً بك مجدداً',
      'student_portal': 'بوابة الطالب',
      'faculty_portal': 'بوابة أعضاء هيئة التدريس',
      'login_title': 'تسجيل الدخول',
      'academic_id': 'الرقم الأكاديمي / كود الطالب',
      'academic_id_hint': 'مثال: 20220451',
      'password': 'كلمة المرور',
      'password_hint': '••••••••',
      'remember_me': 'تذكر بياناتي',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_button': 'دخول النظام',
      'quick_login_student': 'دخول تجريبي (طالب)',
      'quick_login_doctor': 'دخول تجريبي (دكتور/محاضر)',
      
      // Bottom Navigation
      'nav_home': 'الرئيسية',
      'nav_schedule': 'الجدول',
      'nav_grades': 'النتائج',
      'nav_services': 'الخدمات',
      'nav_profile': 'حسابي',

      // Home Dashboard
      'digital_id_btn': 'كارنيه الكلية الرقمي',
      'next_lecture': 'المحاضرة القادمة',
      'starts_in': 'تبدأ خلال',
      'hall': 'مدرج / قاعة',
      'doctor': 'المحاضر',
      'gpa': 'المعدل التراكمي',
      'completed_hours': 'الساعات المنجزة',
      'attendance_rate': 'نسبة الحضور',
      'financial_status': 'حالة المصروفات',
      'paid': 'مسددة',
      'pending': 'مستحقة',
      'quick_actions': 'الوصول السريع',
      'course_reg': 'تسجيل المواد',
      'exam_schedule': 'جدول الامتحانات',
      'enrollment_cert': 'إفادة قيد',
      'complaints': 'المقترحات والشكاوى',
      'announcements': 'أحدث الأخبار والإعلانات',
      'view_all': 'عرض الكل',

      // Digital ID
      'id_card_title': 'البطاقة الجامعية الرقمية',
      'student_name': 'اسم الطالب',
      'institute': 'المعهد',
      'major': 'التخصص',
      'academic_year': 'الفرقة الدراسية',
      'seat_no': 'رقم الجلوس',
      'scan_qr_hint': 'قم بإظهار هذا الرمز عند بوابات الدخول ومكتبة الأكاديمية',
      'live_verification': 'رمز تحقق حي ومحدث',
      'valid_through': 'سارية حتى نهاية العام الجامعي',

      // Schedule
      'weekly_schedule': 'الجدول الأسبوعي',
      'lectures_and_sections': 'المحاضرات والسكاشن',
      'sat': 'السبت',
      'sun': 'الأحد',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'all': 'الكل',
      'lectures_only': 'محاضرات فقط',
      'sections_only': 'سكاشن وعملي',
      'no_classes_today': 'لا توجد محاضرات في هذا اليوم',

      // Grades
      'academic_results': 'كشف النتائج والتقديرات',
      'cumulative_gpa': 'المعدل التراكمي العام',
      'semester_gpa': 'معدل الفصل',
      'honors_status': 'مرتبة الشرف الأكاديمية',
      'excellent': 'ممتاز',
      'very_good': 'جيد جداً',
      'good': 'جيد',
      'coursework': 'أعمال السنة',
      'midterm': 'الميدتيرم',
      'final_exam': 'التحريري النهائي',
      'total': 'المجموع',
      'grade': 'التقدير',
      'points': 'النقاط',
      'credit_hrs': 'ساعات',

      // Services & Finance
      'services_and_finance': 'الخدمات وشؤون الطلاب',
      'tab_finance': 'المصروفات الدراسية',
      'tab_requests': 'الطلبات الإلكترونية',
      'total_fees': 'إجمالي المصروفات السنوية',
      'paid_amount': 'المبلغ المسدد',
      'remaining_amount': 'المبلغ المتبقي',
      'pay_online': 'سداد إلكتروني (فوري / فيزا)',
      'installments': 'أقساط المصروفات',
      'payment_receipt': 'إيصال السداد',
      'request_service': 'تقديم طلب جديد',
      'request_proof_of_enrollment': 'طلب إفادة قيد رسمية',
      'request_grades_statement': 'طلب بيان تقديرات وساعات معتمدة',
      'request_military_delay': 'إثبات قيد للتجنيد (نموذج 2 جند)',
      'request_id_replacement': 'استخراج كارنيه بدل فاقد',
      'status_completed': 'تم التنفيذ ومتاح للاستلام',
      'status_under_review': 'قيد المراجعة الإدارية',
      'request_submitted_successfully': 'تم إرسال طلبك بنجاح وسيتوفر برقم مرجعي',

      // Faculty
      'faculty_dashboard': 'لوحة تحكم الأكاديمي',
      'my_courses': 'المقررات المكلف بتدريسها',
      'open_qr_attendance': 'فتح تسجيل الحضور بالـ QR',
      'record_grades': 'رصد درجات الطلاب',
      'broadcast_announcement': 'نشر تنبيه للمقرر',
      'students_enrolled': 'طالباً مسجلاً',

      // Settings
      'settings': 'الإعدادات واللغة',
      'language': 'اللغة / Language',
      'dark_mode': 'الوضع الليلي',
      'notifications': 'الإشعارات',
      'about_academy': 'عن أكاديمية طيبة',
      'contact_us': 'تواصل معنا والخط الساخن',
      'logout': 'تسجيل الخروج',
      'hotline': 'الخط الساخن: 19572',
      'campus_maadi': 'مقر المعادي: كورنيش النيل، المعادي، القاهرة',
      'campus_giza': 'مقر الجيزة: شارع الهرم، الجيزة',
    },
    'en': {
      'app_title': 'Thebes Integrated Academy',
      'thebes_academy': 'Thebes Academy',
      'welcome_back': 'Welcome Back',
      'student_portal': 'Student Portal',
      'faculty_portal': 'Faculty Portal',
      'login_title': 'Sign In',
      'academic_id': 'Academic ID / Student Code',
      'academic_id_hint': 'e.g. 20220451',
      'password': 'Password',
      'password_hint': '••••••••',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Sign In',
      'quick_login_student': 'Demo Student Login',
      'quick_login_doctor': 'Demo Faculty Login',
      
      // Bottom Navigation
      'nav_home': 'Home',
      'nav_schedule': 'Schedule',
      'nav_grades': 'Grades',
      'nav_services': 'Services',
      'nav_profile': 'Profile',

      // Home Dashboard
      'digital_id_btn': 'Digital Student ID',
      'next_lecture': 'Upcoming Class',
      'starts_in': 'Starts in',
      'hall': 'Hall / Room',
      'doctor': 'Lecturer',
      'gpa': 'Cumulative GPA',
      'completed_hours': 'Completed Hours',
      'attendance_rate': 'Attendance Rate',
      'financial_status': 'Tuition Status',
      'paid': 'Paid',
      'pending': 'Due',
      'quick_actions': 'Quick Actions',
      'course_reg': 'Course Registration',
      'exam_schedule': 'Exam Timetable',
      'enrollment_cert': 'Enrollment Letter',
      'complaints': 'Suggestions & Complaints',
      'announcements': 'News & Announcements',
      'view_all': 'View All',

      // Digital ID
      'id_card_title': 'Digital Student Card',
      'student_name': 'Student Name',
      'institute': 'Institute',
      'major': 'Department',
      'academic_year': 'Academic Year',
      'seat_no': 'Seat Number',
      'scan_qr_hint': 'Scan this dynamic QR code at campus gates & library',
      'live_verification': 'Live Verified Pass',
      'valid_through': 'Valid through academic year',

      // Schedule
      'weekly_schedule': 'Weekly Timetable',
      'lectures_and_sections': 'Lectures & Labs',
      'sat': 'Sat',
      'sun': 'Sun',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'all': 'All',
      'lectures_only': 'Lectures Only',
      'sections_only': 'Sections & Labs',
      'no_classes_today': 'No classes scheduled for today',

      // Grades
      'academic_results': 'Academic Transcripts & Grades',
      'cumulative_gpa': 'Cumulative GPA',
      'semester_gpa': 'Semester GPA',
      'honors_status': 'Dean\'s Honor List',
      'excellent': 'Excellent',
      'very_good': 'Very Good',
      'good': 'Good',
      'coursework': 'Coursework',
      'midterm': 'Midterm',
      'final_exam': 'Final Exam',
      'total': 'Total',
      'grade': 'Grade',
      'points': 'Points',
      'credit_hrs': 'Credit Hrs',

      // Services & Finance
      'services_and_finance': 'Services & Student Affairs',
      'tab_finance': 'Tuition Fees',
      'tab_requests': 'E-Requests',
      'total_fees': 'Total Annual Tuition',
      'paid_amount': 'Paid Amount',
      'remaining_amount': 'Remaining Balance',
      'pay_online': 'Pay Online (Fawry / Visa)',
      'installments': 'Fee Installments',
      'payment_receipt': 'Payment Receipt',
      'request_service': 'Submit Request',
      'request_proof_of_enrollment': 'Proof of Enrollment Letter',
      'request_grades_statement': 'Official Transcript Statement',
      'request_military_delay': 'Military Service Deferment (Form 2)',
      'request_id_replacement': 'Replacement ID Card',
      'status_completed': 'Ready for Pickup',
      'status_under_review': 'Under Review',
      'request_submitted_successfully': 'Request submitted successfully with ref #',

      // Faculty
      'faculty_dashboard': 'Faculty Dashboard',
      'my_courses': 'Teaching Courses',
      'open_qr_attendance': 'Start QR Attendance',
      'record_grades': 'Submit Student Marks',
      'broadcast_announcement': 'Post Course Announcement',
      'students_enrolled': 'Enrolled Students',

      // Settings
      'settings': 'Settings & Preferences',
      'language': 'Language / اللغة',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'about_academy': 'About Thebes Academy',
      'contact_us': 'Contact Us & Hotline',
      'logout': 'Sign Out',
      'hotline': 'Hotline: 19572',
      'campus_maadi': 'Maadi Campus: Nile Corniche, Maadi, Cairo',
      'campus_giza': 'Giza Campus: Al Haram St, Giza',
    }
  };

  static String get(String key, String langCode) {
    if (_localizedValues.containsKey(langCode)) {
      return _localizedValues[langCode]?[key] ?? key;
    }
    return _localizedValues['ar']?[key] ?? key;
  }
}
